language: node_js

services:
- docker
- mongodb

env:
  global:
    - GOOGLE_CLIENT_ID=googleid
    - GOOGLE_CLIENT_SECRET=googlesecret
    - MONGO_USER=user
    - MONGO_PASSWORD=password

before_install:
- docker-compose -f travis-docker-compose.yml up --build

script:
- docker exec -it wcj-backend npm run test -- --coverage