version: "3.7"
services:
  frontend:
    container_name: wcj-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: wcj/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    container_name: wcj-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: wcj/backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
    environment:
      - GOOGLE_CLIENT_ID=googleid
      - GOOGLE_CLIENT_SECRET=googlesecret
      - MONGO_USER=user
      - MONGO_PASSWORD=password
  mongo:
    container_name: wcj-mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
  mongoex:
    container_name: wcj-mongo-express
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
    ports:
      - "8081:8081"
    links:
      - mongo
volumes:
  mongodb_data:
